service: superconnectors-api
variablesResolutionMode: 20210326
plugins:
  - serverless-plugin-monorepo
custom:
  parameter_prefix: superconnectors/${opt:stage}
  function_prefix: superconnectors-${opt:stage}
  api: ${self:custom.function_prefix}-graphql
  role: ${ssm:/${self:custom.parameter_prefix}/api/role}
  connections_table: ${ssm:/${self:custom.parameter_prefix}/api/connections_table}
  subscriptions_table: ${ssm:/${self:custom.parameter_prefix}/api/subscriptions_table}

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  iam:
    role: ${ssm:/${self:custom.parameter_prefix}/api/role}
  lambdaHashingVersion: 20201221

functions:
  graphql: 
    handler: dist/handlers.query
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: playground
          method: any
          cors: true
    environment:
      SLS_ENVIRONMENT: ${opt:stage}
      HANDLER_NAME: ${self:custom.api}
  subscription:
    handler: dist/handlers.subscription
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
    environment:
      SUBSCRIPTIONS_TABLE: ${self:custom.subscriptions_table}
      CONNECTIONS_TABLE: ${self:custom.connections_table}
